# Generated by Django 6.1.1 on 2026-09-16 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0002_rayon'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='dateFabricationProd',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
