# Generated by Django 6.1.1 on 2026-09-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_produit_datefabricationprod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('identifiantSatut', models.AutoField(primary_key=True, serialize=False)),
                ('libelleStatut', models.CharField(max_length=200)),
            ],
        ),
    ]
