# Generated by Django 6.1.1 on 2026-09-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0005_produit_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statut',
            old_name='identifiantSatut',
            new_name='idStatut',
        ),
    ]
