# Generated by Django 6.1.1 on 2026-09-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0006_rename_identifiantsatut_statut_idstatut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='dateFabricationProd',
            new_name='dateFabProd',
        ),
        migrations.AlterField(
            model_name='rayon',
            name='nomRayon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='statut',
            name='libelleStatut',
            field=models.CharField(max_length=100),
        ),
    ]
