# Generated by Django 6.1.1 on 2026-09-24 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0007_rename_datefabricationprod_produit_datefabprod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qte', models.PositiveIntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenir_produit', to='monApp.produit')),
                ('rayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenir_rayon', to='monApp.rayon')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('produit', 'rayon'), name='unique_produit_rayon')],
            },
        ),
    ]
